/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/**
 * MyEclipse Struts
 * Creation date: 07-24-2008
 *
 * XDoclet definition:
 * @struts.form name="AdminLoginForm"
 */
public class AdminLoginForm extends ActionForm {
	/*
	 * Generated fields


	/** password property */
	private String password;

	/** accountnumber property */
	private String accountnumber;

	/*
	 * Generated Methods
	 */

	/**
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	/*public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}*/

	/**
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/**
	 * Returns the password.
	 * @return String
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * Set the password.
	 * @param password The password to set
	 */
	public void setPassword(String password) {
		System.out.println(password);
		this.password = password;
	}

	public String getAccountnumber() {
		return accountnumber;
	}

	public void setAccountnumber(String accountnumber) {
		this.accountnumber = accountnumber;
	}



	/**
	 * Returns the accountnumber.
	 * @return String
	 */


	/**
	 * Set the accountnumber.
	 * @param accountnumber The accountnumber to set
	 */

}