/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/**
 * MyEclipse Struts
 * Creation date: 07-28-2008
 *
 * XDoclet definition:
 * @struts.form name="NewRegistrationForm"
 */
public class NewRegistrationForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** password property */
	private String password;

	/** gender property */
	private String gender;

	/** acctype property */
	private String acctype;

	/** accnumber property */
	private String accnumber;

	/** contact property */
	private String contact;

	/** age property */
	private String age;

	/** occuption property */
	private String occupation;

	/** address property */
	private String address;

	/** dob property */
	private String dob;

	/** cpassword property */
	private String cpassword;

	/** name property */
	private String name;
	private String amount;

	/*
	 * Generated Methods
	 */

	/**
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/**
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/**
	 * Returns the password.
	 * @return String
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * Set the password.
	 * @param password The password to set
	 */
	public void setPassword(String password) {
		this.password = password;
		System.out.println("password " +password);
	}

	/**
	 * Returns the gender.
	 * @return String
	 */
	public String getGender() {
		return gender;
	}

	/**
	 * Set the gender.
	 * @param gender The gender to set
	 */
	public void setGender(String gender) {
		this.gender = gender;
		System.out.println("gender" +gender);
	}

	/**
	 * Returns the acctype.
	 * @return String
	 */
	public String getAcctype() {
		return acctype;
	}

	/**
	 * Set the acctype.
	 * @param acctype The acctype to set
	 */
	public void setAcctype(String acctype) {
		this.acctype = acctype;
		System.out.println("acctype " +acctype);
	}

	/**
	 * Returns the accnumber.
	 * @return String
	 */
	public String getAccnumber() {
		return accnumber;
	}

	/**
	 * Set the accnumber.
	 * @param accnumber The accnumber to set
	 */
	public void setAccnumber(String accnumber) {
		this.accnumber = accnumber;
		System.out.println("accnumber" +accnumber);
	}

	/**
	 * Returns the contact.
	 * @return String
	 */
	public String getContact() {
		return contact;
	}

	/**
	 * Set the contact.
	 * @param contact The contact to set
	 */
	public void setContact(String contact) {
		this.contact = contact;
		System.out.println("contact" +contact);
	}

	/**
	 * Returns the age.
	 * @return String
	 */
	public String getAge() {
		return age;
	}

	/**
	 * Set the age.
	 * @param age The age to set
	 */
	public void setAge(String age) {
		this.age = age;
		System.out.println("age  "+age);
	}

	/**
	 * Returns the occuption.
	 * @return String
	 */
	public String getOccupation() {
		return occupation;
	}

	/**
	 * Set the occuption.
	 * @param occuption The occuption to set
	 */
	public void setOccupation(String occupation) {
		this.occupation = occupation;
		System.out.println("occupation  "+occupation);
	}

	/**
	 * Returns the address.
	 * @return String
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * Set the address.
	 * @param address The address to set
	 */
	public void setAddress(String address) {
		this.address = address;
		System.out.println("address  " +address);
	}

	/**
	 * Returns the dob.
	 * @return String
	 */
	public String getDob() {
		return dob;
	}

	/**
	 * Set the dob.
	 * @param dob The dob to set
	 */
	public void setDob(String dob) {
		this.dob = dob;
		System.out.println("dob "+dob);
	}

	/**
	 * Returns the cpassword.
	 * @return String
	 */
	public String getCpassword() {
		return cpassword;
	}

	/**
	 * Set the cpassword.
	 * @param cpassword The cpassword to set
	 */
	public void setCpassword(String cpassword) {
		this.cpassword = cpassword;
		System.out.println("c password " +cpassword);
	}

	/**
	 * Returns the name.
	 * @return String
	 */
	public String getName() {
		return name;
	}

	/**
	 * Set the name.
	 * @param name The name to set
	 */
	public void setName(String name) {
		this.name = name;
		System.out.println("name  "+name);
	}

	public String getAmount() {
		return amount;
	}

	public void setAmount(String amount) {
		this.amount = amount;
	}
}